import type { AgentConfig, AgentName } from "@stackforge/shared";

export const AGENT_CONFIGS: Record<AgentName, AgentConfig> = {
  planner: {
    name: "planner",
    description: "Resolves stack, project name, and top-level folder structure",
    tokenBudget: 1000,
    model: "openai/gpt-4o-mini",
    maxInputTokens: 900,
    maxOutputTokens: 700,
    minOutputTokens: 220,
    temperature: 0.2,
    compressionLevel: "high",
    budgetOverflowRetries: 2,
    retries: 1,
  },
  schema: {
    name: "schema",
    description: "Designs entities, fields, indexes, and relationships",
    tokenBudget: 1500,
    model: "openai/gpt-4o-mini",
    maxInputTokens: 1200,
    maxOutputTokens: 1100,
    minOutputTokens: 320,
    temperature: 0.1,
    compressionLevel: "medium",
    budgetOverflowRetries: 2,
    retries: 1,
  },
  api: {
    name: "api",
    description: "Plans REST routes, request/response shapes, and auth requirements",
    tokenBudget: 1600,
    model: "openai/gpt-4o-mini",
    maxInputTokens: 950,
    maxOutputTokens: 1200,
    minOutputTokens: 280,
    temperature: 0.1,
    compressionLevel: "medium",
    budgetOverflowRetries: 2,
    retries: 1,
  },
  frontend: {
    name: "frontend",
    description: "Plans pages, React component trees, and routing",
    tokenBudget: 1200,
    model: "openai/gpt-4o-mini",
    maxInputTokens: 900,
    maxOutputTokens: 900,
    minOutputTokens: 250,
    temperature: 0.2,
    compressionLevel: "high",
    budgetOverflowRetries: 2,
    retries: 1,
  },
  devops: {
    name: "devops",
    description: "Plans CI/CD pipelines, deployment targets, Docker, and env vars",
    tokenBudget: 1000,
    model: "openai/gpt-4o-mini",
    maxInputTokens: 700,
    maxOutputTokens: 850,
    minOutputTokens: 180,
    temperature: 0.2,
    compressionLevel: "high",
    budgetOverflowRetries: 3,
    retries: 1,
  },
  reviewer: {
    name: "reviewer",
    description: "Performs consistency checks and flags issues across the full blueprint",
    tokenBudget: 1200,
    model: "openai/gpt-4o-mini",
    maxInputTokens: 850,
    maxOutputTokens: 900,
    minOutputTokens: 220,
    temperature: 0,
    compressionLevel: "high",
    budgetOverflowRetries: 2,
    retries: 1,
  },
};
