import { Octokit } from "@octokit/rest";
import { buildProjectFiles } from "./fileWriter.js";

export type GithubPushProgress = {
  type: "repo_created" | "file_pushed" | "branch_protection";
  message: string;
  filePath?: string;
  repoUrl?: string;
};

/**
 * GitHub repo name constraints:
 * - Max 100 characters
 * - Only alphanumeric, hyphens, underscores, and dots
 * - Cannot start or end with a dot
 * - Cannot contain ".."
 */
const GITHUB_REPO_NAME_REGEX = /^[a-z0-9]([a-z0-9._-]{0,98}[a-z0-9])?$/;

function toKebabCase(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "stackforge-app";
}

/**
 * Validate that a repo name conforms to GitHub naming rules.
 */
function validateRepoName(name: string): void {
  if (name.length === 0) {
    throw new Error("Repository name cannot be empty");
  }
  if (name.length > 100) {
    throw new Error("Repository name cannot exceed 100 characters");
  }
  if (name.includes("..")) {
    throw new Error("Repository name cannot contain '..'");
  }
  if (!GITHUB_REPO_NAME_REGEX.test(name)) {
    throw new Error(`Invalid repository name: "${name}". Use only lowercase alphanumeric characters, hyphens, underscores, and dots.`);
  }
}

/**
 * Validate file paths to prevent directory traversal attacks.
 */
function isPathSafe(filePath: string): boolean {
  const normalized = filePath.replace(/\\/g, "/");
  if (normalized.startsWith("/") || normalized.startsWith("..")) return false;
  if (normalized.includes("/../") || normalized.endsWith("/..")) return false;
  if (normalized.includes("\0")) return false;
  return true;
}

function wait(ms: number): Promise<void> {
  return new Promise((resolve) => {
    setTimeout(resolve, ms);
  });
}

async function emitProgress(
  onProgress: ((event: GithubPushProgress) => Promise<void> | void) | undefined,
  event: GithubPushProgress,
): Promise<void> {
  if (!onProgress) {
    return;
  }

  await onProgress(event);
}

async function ensureMainBranchExists(octokit: Octokit, owner: string, repo: string): Promise<void> {
  try {
    await octokit.repos.getBranch({
      owner,
      repo,
      branch: "main",
    });
    return;
  } catch {
    // Branch does not exist yet. Initialize it below.
  }

  const tree = await octokit.git.createTree({
    owner,
    repo,
    tree: [],
  });

  const commit = await octokit.git.createCommit({
    owner,
    repo,
    message: "chore: initialize main branch",
    tree: tree.data.sha,
  });

  await octokit.git.createRef({
    owner,
    repo,
    ref: "refs/heads/main",
    sha: commit.data.sha,
  });
}

export async function pushToGitHub(
  pipelineOutput: unknown,
  projectName: string,
  githubToken: string,
  onProgress?: (event: GithubPushProgress) => Promise<void> | void,
): Promise<{ repoUrl: string; success: boolean }> {
  const token = githubToken.trim();
  if (token.length === 0) {
    throw new Error("githubToken is required");
  }

  const repoName = toKebabCase(projectName);
  validateRepoName(repoName);
  const octokit = new Octokit({ auth: token });

  const authUser = await octokit.users.getAuthenticated();
  const repo = await octokit.repos.createForAuthenticatedUser({
    name: repoName,
    description: "Generated by StackForge",
    private: false,
    auto_init: false,
  });

  const owner = repo.data.owner?.login ?? authUser.data.login;
  const repoUrl = repo.data.html_url ?? `https://github.com/${owner}/${repoName}`;

  await ensureMainBranchExists(octokit, owner, repoName);

  await emitProgress(onProgress, {
    type: "repo_created",
    message: `Repository created: ${repoUrl}`,
    repoUrl,
  });

  const { files } = buildProjectFiles(pipelineOutput);
  const entries = Object.entries(files)
    .filter(([filePath]) => isPathSafe(filePath))
    .sort(([a], [b]) => a.localeCompare(b));

  if (entries.length === 0) {
    throw new Error("No valid files to push to GitHub");
  }

  for (const [filePath, content] of entries) {
    await octokit.repos.createOrUpdateFileContents({
      owner,
      repo: repoName,
      path: filePath,
      message: "feat: initial project generated by StackForge",
      content: Buffer.from(content, "utf8").toString("base64"),
      branch: "main",
    });

    await emitProgress(onProgress, {
      type: "file_pushed",
      message: `Pushing ${filePath}...`,
      filePath,
    });

    await wait(120);
  }

  await octokit.repos.updateBranchProtection({
    owner,
    repo: repoName,
    branch: "main",
    required_status_checks: null,
    enforce_admins: false,
    required_pull_request_reviews: null,
    restrictions: null,
  });

  await emitProgress(onProgress, {
    type: "branch_protection",
    message: "Branch protection configured for main",
  });

  return {
    repoUrl,
    success: true,
  };
}
